#!/usr/bin/env python2

from hashlib import md5
import subprocess
import sys

# Both os.urandom and ssl.RAND_pseudo_bytes are slow, so use this monstrosity instead
p = subprocess.Popen('openssl enc -aes-128-ctr -pass "pass:$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" < /dev/zero', shell=True, stdout=subprocess.PIPE)
while True:
	rand = p.stdout.read(32 * 1024)
	dig = md5(rand).digest()
	sys.stdout.write(rand)
	sys.stdout.write(dig)
